name: first-workflow

on:
 workflow_dispatch:

jobs:
  first-workflow:
   runs-on: ubuntu-latest

   steps:
    - name: first steps
      run: |
       echo "hello first world"
       echo "hello first time again"
  